#!/bin/bash
# iTerm Setup Commands for 4-Tab Trading System
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "=== iTerm 4-Tab Trading System Setup ==="
echo ""
echo "Tab 1 - REPOSITORY (Trading Bot):"
echo "cd $SCRIPT_DIR"
echo "source .venv/bin/activate"
echo "python3 mnq_live_bot.py --demo --max-trades 100"
echo ""
echo "Tab 2 - BROKER EXCHANGE (API Monitor):"
echo "cd $SCRIPT_DIR"
echo "source .venv/bin/activate"
echo "watch -n 5 'python3 test_tastytrade.py'"
echo ""
echo "Tab 3 - SERVER (Dashboard):"
echo "cd $SCRIPT_DIR"
echo "source .venv/bin/activate"
echo "python3 live_dashboard.py"
echo ""
echo "Tab 4 - LOCAL (Development/Monitoring):"
echo "cd $SCRIPT_DIR"
echo "source .venv/bin/activate"
echo "tail -f trading_session.log"
echo ""
echo "=== Quick Commands ==="
echo "Start all: Run above commands in respective tabs"
echo "Monitor: tail -f trading_session.log"
echo "Test API: python3 test_tastytrade.py"
echo "Kill all: pkill -f 'python3.*mnq_live_bot\|live_dashboard'"