#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
echo "🎯 iTerm 4-Tab Trading System - Quick Reference"
echo "==============================================="
echo ""
echo "📋 COPY THESE COMMANDS INTO YOUR iTerm TABS:"
echo ""
echo "TAB 1 - REPOSITORY (Trading Bot):"
echo "cd $SCRIPT_DIR && ./tab1_repository.sh"
echo ""
echo "TAB 2 - BROKER EXCHANGE (API Monitor):"
echo "cd $SCRIPT_DIR && ./tab2_broker.sh"
echo ""
echo "TAB 3 - SERVER (Dashboard):"
echo "cd $SCRIPT_DIR && ./tab3_server.sh"
echo ""
echo "TAB 4 - LOCAL (Log Monitor):"
echo "cd $SCRIPT_DIR && ./tab4_local.sh"
echo ""
echo "🔧 MANAGEMENT COMMANDS:"
echo "Check status: ps aux | grep -E 'mnq_live_bot|live_dashboard' | grep -v grep"
echo "Stop all: pkill -f 'python3.*mnq_live_bot\|python3.*live_dashboard'"
echo "View logs: tail -f trading_session.log"
echo ""
echo "🎮 iTerm Navigation:"
echo "Switch tabs: Cmd + Shift + [ or ]"
echo "New tab: Cmd + T"
echo "Close tab: Cmd + W"